language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
install:
 - pip install coverage
 - pip install codecov
script: python setup.py build install && coverage run test_bytesop.py
after_success:
  - codecov